name: Ubuntu image CI Build

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build photobooth Ubuntu image"
    runs-on: ubuntu-latest
    steps:
      - name: Update system
        run: |
          sudo apt update
          sudo apt upgrade -y
      - name: Checkout photobooth-image
        uses: actions/checkout@v3
        with:
          path: photobooth-image
      - name: Checkout photobooth
        uses: actions/checkout@v3
        with:
          repository: andi34/photobooth
          submodules: true
          path: photobooth
      - name: Checkout ubuntu from scretch
        uses: actions/checkout@v3
        with:
          repository: mvallim/live-custom-ubuntu-from-scratch
          path: custom-ubuntu
      - name: Build Ubuntu image
        run: |
          cp photobooth-image/image_builder/ubuntu/custom-ubuntu-cfg.sh custom-ubuntu/scripts/config.sh
          cd custom-ubuntu/scripts
          # Setup CHROOT envornment
          ./build.sh setup_host
          # Copy install dependencies
          ls -la
          ls -la chroot
          sudo mkdir -p chroot/root
          sudo cp ../../photobooth/install-raspbian.sh chroot/root/
          ls -la chroot
          ls -la chroot/root
          # Finish install
          ./build.sh debootstrap -
      - name: Compress
        run: |
          cd custom-ubuntu/scripts
          gzip photobooth.iso
      - name: Publish image
        uses: actions/upload-artifact@v2
        with:
          name: photobooth-ubuntu-image
          path: custom-ubuntu/scripts/photobooth.iso.gz
