name: Raspberry image CI Build
on: 
  workflow_dispatch:

jobs:
  rpi-image:
    name: "Build photobooth Raspberry image"
    runs-on: ubuntu-latest
    steps:
      - name: Update system
        run: |
          sudo apt update
          sudo apt upgrade -y
      - name: Checkout photobooth-image
        uses: actions/checkout@v3
        with:
          path: photobooth-image
      - name: Checkout pi-gen
        uses: actions/checkout@v3
        with:
          repository: RPI-Distro/pi-gen
          path: pi-gen
      - name: Install pi-gen dependencies
        run: |
          cat pi-gen/depends | rev | cut -d: -f1 | rev | xargs sudo apt install -y
      # build image using pi-gen
      - name: Build PI image
        run: |
          cp photobooth-image/raspberry/custom-pi-config pi-gen/config
          cp -R photobooth-image/raspberry/stage-photobooth pi-gen/stage-photobooth
          chmod +x pi-gen/stage-photobooth/00-install-photobooth/00-run.sh
          chmod +x pi-gen/stage-photobooth/01-disable-usercreation/00-run.sh
          chmod +x pi-gen/stage-photobooth/02-disable-autologin/00-run.sh
          chmod +x pi-gen/stage-photobooth/prerun.sh
          wget https://raw.githubusercontent.com/andi34/photobooth/dev/install-photobooth.sh -O pi-gen/stage-photobooth/00-install-photobooth/files/install-photobooth.sh
          chmod +x pi-gen/stage-photobooth/00-install-photobooth/files/install-photobooth.sh
          echo "#!/bin/bash -e" > pi-gen/export-image/01-user-rename/01-run.sh
          chmod +x pi-gen/export-image/01-user-rename/01-run.sh
          touch ./pi-gen/stage5/SKIP
          touch ./pi-gen/stage5/SKIP_IMAGES
          touch ./pi-gen/stage2/SKIP_IMAGES
          cd pi-gen
          sudo ./build.sh
      - name: Debug 2
        run: |
          sudo apt install -y tree
          tree ./pi-gen/deploy/
      - name: Publish image
        uses: actions/upload-artifact@v3
        with:
          name: photobooth-raspberry-image
          path: ./pi-gen/deploy/image_*.zip
